version: 0.2

# Infrastructure Tests Buildspec
# ================================
# This buildspec runs infrastructure validation tests after deployment
# - Verifies ECS service is running
# - Checks target group health
# - Validates ALB connectivity
# - Tests application endpoints
#
# Triggered after: Successful deployment to DEV/QA/PROD environments
# Reports results back to deployment pipeline

env:
  variables:
    AWS_DEFAULT_REGION: "eu-north-1"
    HEALTH_CHECK_TIMEOUT: "300"
    HEALTH_CHECK_INTERVAL: "10"

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing test dependencies..."
      - pip install boto3 requests --quiet

  pre_build:
    commands:
      - echo "==================================="
      - echo "Infrastructure Test Suite"
      - echo "==================================="
      - echo "Environment: ${ENVIRONMENT}"
      - echo "ECS Cluster: ${ECS_CLUSTER_NAME}"
      - echo "ECS Service: ${ECS_SERVICE_NAME}"
      - echo "Target Group: ${TARGET_GROUP_ARN}"
      - echo "ALB DNS: ${ALB_DNS_NAME}"
      - echo ""

  build:
    commands:
      - echo "==================================="
      - echo "1. ECS Service Health Check"
      - echo "==================================="
      - |
        python3 << 'EOF'
        import boto3
        import sys
        import os
        import time
        
        ecs = boto3.client('ecs', region_name=os.environ['AWS_DEFAULT_REGION'])
        cluster = os.environ['ECS_CLUSTER_NAME']
        service = os.environ['ECS_SERVICE_NAME']
        
        print(f"Checking ECS service: {service} in cluster: {cluster}")
        
        try:
            response = ecs.describe_services(cluster=cluster, services=[service])
            
            if not response['services']:
                print(f"❌ ERROR: Service {service} not found")
                sys.exit(1)
            
            service_data = response['services'][0]
            status = service_data['status']
            desired = service_data['desiredCount']
            running = service_data['runningCount']
            
            print(f"Service Status: {status}")
            print(f"Desired Count: {desired}")
            print(f"Running Count: {running}")
            
            if status != 'ACTIVE':
                print(f"❌ ERROR: Service is not ACTIVE (current: {status})")
                sys.exit(1)
            
            if running < desired:
                print(f"⚠️  WARNING: Running count ({running}) is less than desired ({desired})")
                print("Waiting for tasks to start...")
                
                # Wait up to 5 minutes for tasks to become healthy
                timeout = int(os.environ.get('HEALTH_CHECK_TIMEOUT', 300))
                interval = int(os.environ.get('HEALTH_CHECK_INTERVAL', 10))
                elapsed = 0
                
                while running < desired and elapsed < timeout:
                    time.sleep(interval)
                    elapsed += interval
                    response = ecs.describe_services(cluster=cluster, services=[service])
                    running = response['services'][0]['runningCount']
                    print(f"Running count: {running}/{desired} (waited {elapsed}s)")
                
                if running < desired:
                    print(f"❌ ERROR: Service did not reach desired count within {timeout} seconds")
                    sys.exit(1)
            
            print("✅ ECS Service is healthy")
            
        except Exception as e:
            print(f"❌ ERROR: {str(e)}")
            sys.exit(1)
        EOF
      
      - echo ""
      - echo "==================================="
      - echo "2. Target Group Health Check"
      - echo "==================================="
      - |
        python3 << 'EOF'
        import boto3
        import sys
        import os
        import time
        
        elbv2 = boto3.client('elbv2', region_name=os.environ['AWS_DEFAULT_REGION'])
        target_group_arn = os.environ['TARGET_GROUP_ARN']
        
        print(f"Checking target group: {target_group_arn}")
        
        try:
            # Wait for targets to become healthy
            timeout = int(os.environ.get('HEALTH_CHECK_TIMEOUT', 300))
            interval = int(os.environ.get('HEALTH_CHECK_INTERVAL', 10))
            elapsed = 0
            all_healthy = False
            
            while not all_healthy and elapsed < timeout:
                response = elbv2.describe_target_health(TargetGroupArn=target_group_arn)
                targets = response['TargetHealthDescriptions']
                
                if not targets:
                    print("⚠️  No targets registered yet, waiting...")
                    time.sleep(interval)
                    elapsed += interval
                    continue
                
                healthy_count = sum(1 for t in targets if t['TargetHealth']['State'] == 'healthy')
                total_count = len(targets)
                
                print(f"Healthy targets: {healthy_count}/{total_count}")
                
                for target in targets:
                    target_id = target['Target']['Id']
                    state = target['TargetHealth']['State']
                    reason = target['TargetHealth'].get('Reason', 'N/A')
                    print(f"  - Target {target_id}: {state} ({reason})")
                
                if healthy_count == total_count and total_count > 0:
                    all_healthy = True
                    print("✅ All targets are healthy")
                    break
                
                if elapsed < timeout:
                    print(f"Waiting for targets to become healthy... ({elapsed}s elapsed)")
                    time.sleep(interval)
                    elapsed += interval
            
            if not all_healthy:
                print(f"❌ ERROR: Not all targets became healthy within {timeout} seconds")
                sys.exit(1)
                
        except Exception as e:
            print(f"❌ ERROR: {str(e)}")
            sys.exit(1)
        EOF
      
      - echo ""
      - echo "==================================="
      - echo "3. Application Load Balancer Check"
      - echo "==================================="
      - |
        python3 << 'EOF'
        import requests
        import sys
        import os
        import time
        
        alb_dns = os.environ['ALB_DNS_NAME']
        health_endpoint = f"http://{alb_dns}/actuator/health"
        
        print(f"Testing ALB endpoint: {health_endpoint}")
        
        try:
            # Give ALB a moment to update routing
            print("Waiting 10 seconds for ALB to update routing...")
            time.sleep(10)
            
            response = requests.get(health_endpoint, timeout=30)
            
            print(f"Response Status: {response.status_code}")
            print(f"Response Body: {response.text}")
            
            if response.status_code != 200:
                print(f"❌ ERROR: Health endpoint returned status {response.status_code}")
                sys.exit(1)
            
            # Check if response contains expected health check data
            if 'status' in response.text.lower():
                print("✅ ALB is routing traffic correctly")
            else:
                print("⚠️  WARNING: Unexpected response format")
                
        except requests.exceptions.Timeout:
            print("❌ ERROR: Request to ALB timed out")
            sys.exit(1)
        except Exception as e:
            print(f"❌ ERROR: {str(e)}")
            sys.exit(1)
        EOF
      
      - echo ""
      - echo "==================================="
      - echo "4. Application Endpoints Test"
      - echo "==================================="
      - |
        python3 << 'EOF'
        import requests
        import sys
        import os
        
        alb_dns = os.environ['ALB_DNS_NAME']
        base_url = f"http://{alb_dns}"
        
        endpoints = [
            {"path": "/actuator/health", "description": "Health Check"},
            {"path": "/actuator/info", "description": "Application Info"},
        ]
        
        failed = False
        
        for endpoint in endpoints:
            url = base_url + endpoint['path']
            print(f"Testing {endpoint['description']}: {url}")
            
            try:
                response = requests.get(url, timeout=30)
                if response.status_code == 200:
                    print(f"  ✅ {endpoint['description']} - OK")
                else:
                    print(f"  ⚠️  {endpoint['description']} - Status {response.status_code}")
            except Exception as e:
                print(f"  ❌ {endpoint['description']} - ERROR: {str(e)}")
                failed = True
        
        if failed:
            print("\n❌ Some endpoints failed")
            sys.exit(1)
        else:
            print("\n✅ All application endpoints are responsive")
        EOF

  post_build:
    commands:
      - echo ""
      - echo "==================================="
      - echo "Infrastructure Tests Complete"
      - echo "==================================="
      - |
        if [ $CODEBUILD_BUILD_SUCCEEDING -eq 1 ]; then
          echo "✅ All infrastructure tests PASSED"
          echo "Environment ${ENVIRONMENT} is healthy and ready"
          exit 0
        else
          echo "❌ Infrastructure tests FAILED"
          echo "Please check the logs above for details"
          exit 1
        fi

artifacts:
  files:
    - '**/*'
  name: infrastructure-test-results
