version: 0.2

# Infrastructure Tests Buildspec
# ================================
# This buildspec runs infrastructure validation tests after deployment
# Uses Maven to execute infrastructure test classes
#
# Triggered after: Successful deployment to DEV/QA/PROD environments
# Reports results back to deployment pipeline

phases:
  install:
    runtime-versions:
      java: corretto21

  pre_build:
    commands:
      - echo "==================================="
      - echo "Infrastructure Test Suite"
      - echo "==================================="
      - echo "Environment: ${ENVIRONMENT}"
      - echo ""

  build:
    commands:
      - echo "Running infrastructure tests..."
      - ./mvnw test -B -q -Dtest='**/*Infrastructure*Test'

artifacts:
  files:
    - '**/*'
  name: infrastructure-test-results
