# Checkov Security Configuration
# =================================
# This file suppresses specific security checks that are intentional design decisions
# or expensive optional features not required for this application.

skip-check:
  # ========================================================================
  # INTENTIONAL DESIGN DECISIONS (Required for Application Functionality)
  # ========================================================================
  
  # CKV_AWS_260: ALB Security Group allows HTTP (port 80)
  # REASON: Required for HTTP-to-HTTPS redirect functionality
  # IMPACT: ALB needs to accept HTTP traffic on port 80 to redirect users to HTTPS
  # SECURITY: Traffic is immediately redirected to HTTPS, no data exposure
  - CKV_AWS_260

  # CKV_AWS_378: ALB Target Group uses HTTP protocol  
  # REASON: Standard microservices pattern - ALB terminates SSL, forwards HTTP to containers
  # IMPACT: ECS containers run HTTP internally (port 8080), ALB handles SSL termination
  # SECURITY: Internal VPC traffic only, protected by security groups
  - CKV_AWS_378

  # CKV2_AWS_12: Default VPC Security Group allows traffic
  # REASON: AWS default behavior, VPC is secured with custom security groups
  # IMPACT: Default SG exists but isn't used by any resources
  # SECURITY: All resources use custom security groups with proper restrictions
  - CKV2_AWS_12

  # CKV_AWS_150: Load Balancer deletion protection disabled
  # REASON: Deletion protection disabled for easier terraform destroy in dev/test environments
  # IMPACT: Load balancers can be destroyed via terraform without manual intervention
  # SECURITY: Protected by Terraform state management, version control, and IAM permissions
  # JUSTIFICATION: Development environments require frequent deployment/teardown cycles
  - CKV_AWS_150

  # ========================================================================
  # EXPENSIVE OPTIONAL FEATURES (Cost vs. Benefit Analysis)
  # ========================================================================
  
  # CKV_AWS_144: S3 Cross-Region Replication
  # REASON: Expensive optional disaster recovery feature
  # COST: Doubles storage costs + cross-region transfer fees
  # IMPACT: Only needed for specific DR requirements or compliance mandates
  # ALTERNATIVE: S3 versioning and backup strategies already implemented
  - CKV_AWS_144

  # CKV2_AWS_62: S3 Event Notifications for Audit Logging Buckets
  # REASON: Event notifications not required for audit logging buckets
  # COST: Additional SNS/SQS costs for notifications on every log file
  # IMPACT: Audit logs are write-only storage, notifications add complexity without benefit
  # ALTERNATIVE: CloudTrail and access logging provide sufficient audit trail
  - CKV2_AWS_62

  # CKV_AWS_272: Lambda Code Signing Configuration
  # REASON: Code signing requires AWS Signer service and signing profiles
  # IMPACT: Lambda functions run without code signing validation
  # ALTERNATIVES: CI/CD pipeline provides code integrity validation
  # COST: AWS Signer service incurs additional costs for signing operations
  - CKV_AWS_272

  # ========================================================================
  # DEPLOYMENT-SPECIFIC EXCEPTIONS (Based on Applied Configuration)
  # ========================================================================
  
  # CKV_AWS_91: ALB access logging disabled
  # REASON: S3 permission complexity and ALB logging race conditions during deployment
  # IMPACT: ALB access logs not stored to S3 bucket
  # LEARNED: ALB service account permissions require careful timing with bucket policy
  # TEMPORARY: Could be re-enabled once bucket permissions are stable
  - CKV_AWS_91

  # CKV_AWS_2: ALB using HTTP instead of HTTPS  
  # REASON: Certificate complexity and development environment simplification
  # IMPACT: Load balancer accepts HTTP traffic on port 80
  # LEARNED: HTTPS redirect was causing 403 errors during testing
  # ENVIRONMENT: Acceptable for development, should be HTTPS in production
  - CKV_AWS_2

  # CKV_AWS_103: ALB not using TLS 1.2+
  # REASON: HTTP listener used instead of HTTPS for development
  # IMPACT: No TLS security on load balancer listener
  # CORRELATION: Related to CKV_AWS_2 above
  - CKV_AWS_103

  # CKV2_AWS_20: No HTTP to HTTPS redirect
  # REASON: HTTPS functionality disabled for development environment
  # IMPACT: HTTP requests not automatically redirected to HTTPS
  # LEARNED: HTTPS redirect was blocking API requests during testing
  - CKV2_AWS_20

  # CKV2_AWS_28: ALB not protected by WAF
  # REASON: WAF was blocking legitimate requests and causing 403 errors
  # IMPACT: Application Load Balancer not protected by Web Application Firewall
  # LEARNED: WAF rules were too restrictive for image upload API endpoints
  # SOLUTION: WAF association disabled to allow API functionality
  - CKV2_AWS_28

  # CKV2_AWS_31: WAF2 has no logging configuration
  # REASON: WAF entirely disabled due to request blocking issues
  # IMPACT: No WAF logs generated
  # CORRELATION: Related to CKV2_AWS_28 - WAF not used
  - CKV2_AWS_31

  # CKV_AWS_111: IAM write access without constraints
  # REASON: Lambda needs broad permissions for image processing pipeline
  # IMPACT: Lambda has extensive write permissions across AWS services
  # JUSTIFICATION: Required for S3→SNS→SQS→Lambda→DynamoDB workflow
  # SERVICES: Needs access to S3, DynamoDB, SQS, SNS, KMS, CloudWatch
  - CKV_AWS_111

  # CKV_AWS_356: IAM policy using "*" resources
  # REASON: Lambda processes images with dynamic S3 bucket names and keys
  # IMPACT: IAM policy uses wildcarded resources for flexibility
  # JUSTIFICATION: Image processing requires dynamic resource access patterns
  # LEARNED: Specific resource ARNs not feasible for user-generated content
  - CKV_AWS_356

  # CKV_AWS_115: Lambda function-level concurrent execution limit
  # REASON: Auto-scaling preferred for variable image processing workloads
  # IMPACT: Lambda can scale without function-level concurrency constraints
  # LEARNED: SQS-triggered Lambda should scale dynamically based on queue depth
  # PERFORMANCE: Unlimited scaling provides better user experience
  - CKV_AWS_115

  # ========================================================================
  # TECH DEBT - CI/CD Infrastructure Issues (To be fixed later)
  # ========================================================================
  
  # CKV_AWS_314: CodeBuild project environments missing logging configuration
  # REASON: Tech debt - logging configuration not yet implemented
  # IMPACT: CodeBuild logs only go to CloudWatch Logs, not S3
  # TODO: Add S3 bucket logging configuration for long-term log retention
  - CKV_AWS_314

  # CKV_AWS_147: CodeBuild projects not encrypted with CMK
  # REASON: Tech debt - using AWS managed keys instead of customer managed keys
  # IMPACT: Build artifacts encrypted but not with custom KMS CMK
  # TODO: Create KMS CMK for CodeBuild encryption
  - CKV_AWS_147

  # CKV_AWS_316: CodeBuild privileged mode enabled
  # REASON: Required for Docker builds within CodeBuild
  # IMPACT: Build container runs with elevated privileges
  # JUSTIFICATION: Needed for terraform and docker operations in CI/CD
  - CKV_AWS_316

  # CKV_AWS_219: CodePipeline artifact store not using KMS CMK
  # REASON: Tech debt - using default S3 encryption instead of CMK
  # IMPACT: Pipeline artifacts encrypted with AWS managed keys
  # TODO: Configure KMS CMK for CodePipeline S3 bucket
  - CKV_AWS_219

  # CKV_AWS_300: S3 lifecycle missing abort incomplete multipart upload rule
  # REASON: Tech debt - lifecycle configuration incomplete
  # IMPACT: Failed multipart uploads not automatically cleaned up
  # TODO: Add abort_incomplete_multipart_upload_days to lifecycle rules
  - CKV_AWS_300

  # CKV_AWS_355: IAM policies allow "*" as resource for restrictable actions
  # REASON: Tech debt - overly broad IAM permissions in deploy policy
  # IMPACT: CodeBuild deploy has broader permissions than needed
  # TODO: Restrict to specific resource ARNs where possible
  - CKV_AWS_355

  # CKV_AWS_290: IAM policy allows write access without constraints
  # REASON: Tech debt - deploy policy needs refactoring for least privilege
  # IMPACT: CodeBuild can write to more resources than strictly necessary
  # TODO: Implement resource-level and condition-based restrictions
  - CKV_AWS_290

  # CKV_AWS_288: IAM policy allows potential data exfiltration
  # REASON: Tech debt - PR validation policy needs tightening
  # IMPACT: Could theoretically read/write sensitive data
  # TODO: Add condition keys and resource restrictions
  - CKV_AWS_288

  # CKV_AWS_18: CI/CD artifact S3 buckets missing access logging
  # REASON: Tech debt - access logging not configured for artifact buckets
  # IMPACT: No audit trail of who accessed CI/CD artifacts
  # TODO: Create separate log bucket and enable S3 access logging
  - CKV_AWS_18

  # CKV_AWS_145: CI/CD artifact S3 buckets not using KMS encryption
  # REASON: Tech debt - using default S3 encryption instead of CMK
  # IMPACT: Artifacts encrypted but not with customer managed key
  # TODO: Configure KMS CMK for artifact bucket encryption
  - CKV_AWS_145

# Configuration Options
framework: terraform
compact: true
quiet: false

# Optional: Suppress entire directories if needed
# skip-path:
#   - /legacy/
#   - /temp/

# Optional: Set severity threshold (LOW, MEDIUM, HIGH, CRITICAL)
# check-threshold: HIGH