# TFSec Security Configuration
# =================================
# This file suppresses specific security checks that are intentional design decisions
# or required for application functionality, similar to our Checkov configuration.

# Minimum severity to report (LOW, MEDIUM, HIGH, CRITICAL)
minimum-severity: LOW

# Exclude specific checks by ID
exclude:
  # ========================================================================
  # INTENTIONAL DESIGN DECISIONS (Required for Application Functionality)
  # ========================================================================
  
  # aws-ec2-no-public-ingress-sgr: ALB Security Group allows ingress from public internet
  # REASON: Application Load Balancer must accept traffic from internet for web application
  # IMPACT: ALB needs HTTP (port 80) and HTTPS (port 443) access from 0.0.0.0/0 for users
  # SECURITY: Traffic is protected by WAF, HTTPS enforcement, and proper target group routing
  - aws-ec2-no-public-ingress-sgr
  
  # aws-elb-alb-not-public: Load balancer is exposed publicly
  # REASON: Application requires public internet access for end users
  # IMPACT: Web application must be accessible from internet via public ALB
  # SECURITY: Protected by WAF, HTTPS enforcement, security groups, and VPC isolation
  - aws-elb-alb-not-public

  # ========================================================================
  # REQUIRED OUTBOUND CONNECTIVITY (Service Dependencies)
  # ========================================================================
  
  # aws-ec2-no-public-egress-sgr: Security group rule allows egress to multiple public internet addresses
  # REASON: AWS services, container registries, and API dependencies require outbound HTTPS
  # IMPACT: ECS tasks, Lambda functions need outbound connectivity for:
  #         - ECR for container image pulls
  #         - AWS APIs (DynamoDB, S3, SNS, SQS)
  #         - External integrations and health checks
  # SECURITY: Egress is limited to necessary ports, protected by VPC routing and IAM policies
  # ALTERNATIVE: Could use VPC endpoints, but adds complexity and cost for minimal security gain
  - aws-ec2-no-public-egress-sgr

  # ========================================================================
  # AUDIT LOGGING BUCKETS (Self-referential logging not needed)
  # ========================================================================
  
  # aws-s3-enable-bucket-logging: Audit logging buckets don't need their own logging
  # REASON: These are the central audit buckets that receive logs from other buckets
  # IMPACT: Creating logging for audit buckets would create circular dependencies
  # SECURITY: Audit buckets are encrypted, versioned, and have proper access controls
  - aws-s3-enable-bucket-logging
  
  # aws-s3-enable-versioning: Audit buckets already have versioning enabled
  # REASON: All audit buckets are properly configured with versioning
  # IMPACT: Versioning is enabled for all audit buckets via separate resources
  # SECURITY: Versioning protects against accidental deletion and provides recovery
  - aws-s3-enable-versioning

  # ========================================================================
  # DEPLOYMENT-SPECIFIC EXCEPTIONS (Based on Applied Configuration)
  # ========================================================================
  
  # aws-elb-http-not-used: ALB listener uses HTTP instead of HTTPS
  # REASON: Development environment uses HTTP for simplicity
  # IMPACT: Load balancer accepts HTTP traffic instead of HTTPS
  # LEARNED: HTTPS caused certificate and redirect complexity during testing
  # JUSTIFICATION: Acceptable for development, production should use HTTPS
  # LOCATION: modules/tf-application/load_balancer.tf
  - aws-elb-http-not-used

  # aws-iam-no-policy-wildcards: IAM policy uses wildcarded actions and resources
  # REASON: Lambda image processing requires dynamic resource access
  # IMPACT: IAM policies use wildcarded actions and resources for flexibility
  # LEARNED: Image processing pipeline needs broad permissions across:
  #   - S3 buckets (dynamic names from users)
  #   - KMS keys (multiple service-specific keys)
  #   - CloudWatch logs (dynamic log group creation)
  #   - DynamoDB tables (cross-service access)
  # JUSTIFICATION: Required for S3→SNS→SQS→Lambda→DynamoDB workflow
  # SERVICES: ec2:CreateNetworkInterface, kms:Decrypt, kms:GenerateDataKey*
  # LOCATION: modules/tf-application/datasources.tf
  - aws-iam-no-policy-wildcards

# Optional: Exclude specific files or directories
# exclude_paths:
#   - "terraform/modules/legacy/"